FORMAT: 1A
HOST: https://api.sac.digital

# Criar Contactos


## Questions Collection [/v2/client/contact/import]


### Importar Contato [POST]

Metodo para criar contato

+ Request (application/json)


+ Response 201 (application/json)

    + Headers


    + Body